<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="apples-MacBook-Pro-3.local" failures="3" tests="14" name="com.sentieo.mobile.MobileFinanceApi" time="5.606" errors="0" timestamp="2020-05-31T12:19:29 IST" skipped="11">
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchLivePrice" time="1.722">
    <failure message="expected [100] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [100] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.sentieo.mobile.MobileFinanceApi.fetchLivePrice(MobileFinanceApi.java:310)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- fetchLivePrice -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchLivePrice" time="2.360">
    <failure message="expected [100] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [100] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.sentieo.mobile.MobileFinanceApi.fetchLivePrice(MobileFinanceApi.java:310)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- fetchLivePrice -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchLivePrice" time="1.524">
    <failure message="expected [100] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [100] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.sentieo.mobile.MobileFinanceApi.fetchLivePrice(MobileFinanceApi.java:310)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- fetchLivePrice -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="mobileStockData">
    <skipped/>
  </testcase> <!-- mobileStockData -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchGraphDataYearlyChart">
    <skipped/>
  </testcase> <!-- fetchGraphDataYearlyChart -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="comparableSearch">
    <skipped/>
  </testcase> <!-- comparableSearch -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="financialStatement1">
    <skipped/>
  </testcase> <!-- financialStatement1 -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchGraphDataFinMatrices">
    <skipped/>
  </testcase> <!-- fetchGraphDataFinMatrices -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="financialStatement">
    <skipped/>
  </testcase> <!-- financialStatement -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchGraphDataPriceChart">
    <skipped/>
  </testcase> <!-- fetchGraphDataPriceChart -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchValueTable">
    <skipped/>
  </testcase> <!-- fetchValueTable -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchPastIntra">
    <skipped/>
  </testcase> <!-- fetchPastIntra -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="financialModel">
    <skipped/>
  </testcase> <!-- financialModel -->
  <system-out/>
  <testcase classname="com.sentieo.mobile.MobileFinanceApi" name="fetchGraphDataEstimateTrends">
    <skipped/>
  </testcase> <!-- fetchGraphDataEstimateTrends -->
  <system-out/>
</testsuite> <!-- com.sentieo.mobile.MobileFinanceApi -->
